### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by daron4ever** [marcelovsantos/atom-copy-highlighted#3] opened 2018-02-03 18:48 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.3
**Thrown From**: [copy-highlighted](https://github.com/marcelovsantos/atom-copy-highlighted) package 0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of null

```
At /Users/saehoondannykim/.atom/packages/copy-highlighted/lib/copy-highlighted.js:38

TypeError: Cannot read property 'path' of null
    at Object.copy (/packages/copy-highlighted/lib/copy-highlighted.js:38:41)
    at HTMLElement.copyHighlightedCopy (/packages/copy-highlighted/lib/copy-highlighted.js:23:49)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1399:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:348:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:34.5.0 core:paste (input.hidden-input)
     -0:32.4.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:29.8.0 core:confirm (input.hidden-input)
     -0:21.2.0 copy-highlighted:copy (span.syntax--meta.syntax--arguments.syntax--js)
```

### Non-Core Packages

```
atom-html-preview 0.2.5 
copy-highlighted 0.2.0 
file-icons 2.1.16 
pigments 0.40.2 
remote-ftp 2.1.4 
```

**Comment by marcelovsantos** [comment] 2018-02-04 21:21
Duplicate of #1

**Closed as completed by marcelovsantos** 2018-02-04 21:21 UTC
